#!/usr/bin/env bash
#
# 	The following EC Agent Gateway, Server and Client commands
# 	are intended to be used as templates for basic 
# 	use cases. Further down you will find a reference 
# 	guide for all the flags found within the commands.
#	While written with Linux/Mac agents in mind,
#	these commands require very little adjustments
#	to be 'copy/paste' ready for a Windows environment.
#
# the ZON is the 'guid' of the service, which is found in the service key or with `cf s <your-service-instance-name` --guid
ZON=

# the SST is the uri of the service instance app (apis used by the agents), ending in 'predix.io', not '/v1/index'
SST=
# cleanup $SST in case previous instructions were missed
SST=${SST///v1*}

# the TKN is the admin token of the service, found in the service key
TKN=

# the IDs used by the server/client agents belong to a named 'group' (string), the starting default group name is the GUID or 'Zone' of the Service subscription 
GRP=${ZON}

# the CLIENT_ID is the ID for the EC Client
CLIENT_ID=

# the SERVER_ID is the ID for the EC Server
SERVER_ID=

# the CID is the uaa 'client ID' setup and configured for this EC Service subscription
CID=

# the CSC is the uaa 'client secret' associated with the CID value
CSC=

# the DUR is the auto-refresh time for the server and client agents, this must be lower than the expiration value of tokens for the uaa client id, or the token will expire and connectivity will be broken 
DUR=3000

# the OA2 is the /oauth/token endpoint of the uaa instance that the server and client agents use to fetch and refresh bearer tokens
OA2=

# the HST refers to the gateway agent app on Predix (or elsewhere), when running locally, this must be ws: protocol
HST=

# the RHT is the IP or host address of the resource you wish to access with EC via the server agent
RHT=

# the RPT is the port used to access the RHT value, e.g. 5432 for most postgres instances
RPT=

# the LPT is the port the client will listen on locally
LPT=7990

# the GPT is the Gateway's listening port, '${PORT}' should be used for gateway agents running on Predix
GPT=8080

# the HCA refers to the port the /health check will use, this is only needed explicitly in Server and Client modes
HCA=8080


# -----------------------------------------------------
# 				Gateway Agent   
# -----------------------------------------------------
#
# ./ecagent_linux_sys \
# -mod gateway \
# -gpt $GPT \
# -zon $ZON \
# -sst $SST \
# -tkn $TKN
#
#
# -----------------------------------------------------
# 				Server Agent
# -----------------------------------------------------
#
# ./ecagent_linux_sys \
# -mod server \
# -aid $SERVER_ID \
# -grp $GRP \
# -cid $CID \
# -csc $CSC \
# -dur $DUR \
# -oa2 $OA2 \
# -hst $HST \
# -zon $ZON \
# -sst $SST \
# -rht $RHT \
# -rpt $RPT \
# -hca $HCA
#
#
# -----------------------------------------------------
# 				Client Agent
# -----------------------------------------------------
#
# ./ecagent_linux_sys \
# -mod client \
# -aid $CLIENT_ID \
# -tid $SERVER_ID \
# -grp $GRP \
# -cid $CID \
# -csc $CSC \
# -dur $DUR \
# -oa2 $OA2 \
# -hst $HST \
# -lpt $LPT
#
#
# -----------------------------------------------------
# 				GW:Server Fuse Agent
# -----------------------------------------------------
#
# ./ecagent_linux_sys \
# -mod gw:server \
# -gpt $GPT \
# -zon $ZON \
# -sst $SST \
# -tkn $TKN \
# -aid $SERVER_ID \
# -grp $GRP \
# -rht $RHT \
# -rpt $RPT
#
#
# -----------------------------------------------------
# 				GW:Client Fuse Agent
# -----------------------------------------------------
#
# ./ecagent_linux_sys \
# -mod gw:client \
# -gpt ${PORT} \
# -zon $ZON \
# -sst $SST \
# -tkn $TKN \
# -hst $HST \
# -aid $CLIENT_ID \
# -tid $SERVER_ID \
# -grp $GRP \
# -lpt $LPT
#
#
# -----------------------------------------------------
# 	  GW:Server Two-Process Agent (not-recommended)
# -----------------------------------------------------
#
# ./ecagent_linux_sys \
# -mod gateway \
# -gpt $GPT \
# -zon $ZON \
# -sst $SST \
# -tkn $TKN &
# sleep 1;
# ./ecagent_linux_sys \
# -mod server \
# -aid $SERVER_ID \
# -grp $GRP \
# -cid $CID \
# -csc $CSC \
# -dur $DUR \
# -oa2 $OA2 \
# -hst $HST \
# -zon $ZON \
# -sst $SST \
# -rht $RHT \
# -rpt $RPT
#
#
# -----------------------------------------------------
# 				Flag Usage Guide
# -----------------------------------------------------
# 	-flag arg
# 		Description: of flag and arg, if any.
#
#	(also available by running `ecagent_*_sys -h`)
# -----------------------------------------------------
#
# -aid string
# 	Agent ID: Six character, alphanumeric value generated by the Service, 
#	used by the Gateway to identify and vaidate the agent
#
# -bkl string
# 	Black List: Specify comma-separated IPs to be blocked in IPv4/IPv6 format. 
#	E.g. 10.20.30.5, 2002:4559:1FE2::4559:1FE2
#
# -cid string
# 	(UAA) Client ID: The name of the UAA Client configured for EC agents to 
#	auto-refresh the OAuth2 token.
#
# -crt string
# 	Cert: Specify the relative path of a digital certificate to operate the EC agent. 
#	(.pfx, .cer, .p7s, .der, .pem, .crt)
#
# -csc string
# 	(UAA) Client Secret: The 'secret' of the UAA Client configured for EC agents to 
#	auto-refresh the OAuth2 token.
#
# -dbg
# 	Debug: Enables a debug logging mode, which produces additional log output for any EC agent.
#
# -dur int
# 	Duration: How frequently, in seconds, the EC Client or Server will refresh the token.
#
# -gen
# 	Generate a certificate request for the usage validation purpose.
#
# -grp string
# 	Group: The 'group' that the provided -aid/-tid values belong to. 
#	Custom groups can be viewed at the Service's Swagger APIs.
#
# -hca string
# 	Health Check: Specify an available port to enable a health check. 
#	The api is available at <agent_uri>/health.
#
# -hst string
# 	Host: The EC Gateway's URI. 
#	E.g. wss://my-gateway.the-cloud.com/agent; ws://localhost:8080/agent
#
# -inf
# 	The Product Information.
#
# -lpt string
# 	Listening Port: An available port for the agent to listen on when 
#	running in Client or Gateway mode.
#
# -mod string
# 	Mode: The desired operational mode for the EC agent, "client", "server", or "gateway".
#
# -oa2 string
# 	UAA Token Endpoint: E.g. https://my-uaa-instance.predix.io/oauth/token
#
# -plg *** MUST BE FINAL FLAG WHEN USED *** 
# 	Plugins: Enables plugins. This requires the plugins.yml file presented in the agent path.
#
# -pxy string
# 	Proxy: Specify a local proxy service, passwords/data can not be passed. 
#	E.g. http://hello.world.com:8080
#
# -rht string
# 	Resource Host: The 'address' where the EC Server agent can access the desired data/resource. 
#	E.g. <someip>, <somedomain>.
# 
# -rpt string
# 	Resource Port: The port made available by the resource. E.g. 1521, 5432, 8989, 38989
#
# -sgn
# 	Sign: Start a CA Cert-Signing process.
#
# -shc
# 	Secure Health Check: Specify an available port to enable a health check. 
#	The api is available at <agent_uri>/health, and requires basic authentication.
#
# -sst string
# 	Service URI: The EC agents will use this value to make API calls, found in service keys or VCAPs. 
#	E.g. https://7497fbcb-cde5-48ae-aa96-6095371a0e54.run.something.predix.io
#
# -tid string
# 	Target ID: The agent ID of the EC Server the EC Client should connect to.
#
# -tkn string
# 	Token: Generated by the Service upon subscription, this encoded value can be found in either a service key
#	or VCAP, and is the basic auth for the Service APIs.
#
# -ver
# 	Output version information
#
# -vfy
# 	Verify the legitimacy of a digital certificate.
#
# -wtl string
# 	White List: Specify comma-separated IPs to be white-listed in CIDR format. 
#	E.g. 89.24.9.0/24, 7.6.0.0/16 (default "0.0.0.0/0,::/0")
#
# -zon string
# 	Zone: GUID of the EC Service. This value can be found in the service key, vcaps, or by running:
#	$ cf service SERVICE_NAME --guid
